# Generated by Django 4.0.4 on 2022-06-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('qualification', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('alternateno', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('source', models.CharField(max_length=10)),
                ('experience', models.CharField(max_length=10)),
                ('plan', models.CharField(max_length=10)),
                ('job', models.CharField(max_length=10)),
                ('batch', models.CharField(max_length=10)),
            ],
        ),
    ]
